version: '2'

services:
    customer-services:
        build:
            context: .\ProductMicroServices\ServicesGroup\CustomerServices
            dockerfile: .\Dockerfile
        networks:
          - backend
        ports:
            - "8090:80"

    product-services:
        build:
            context: .\ProductMicroServices\ServicesGroup\ProductServices
            dockerfile: .\Dockerfile
        networks:
          - backend
        ports:
            - "8092:80"
    customer-order-services:
        build:
            context: .\ProductMicroServices\ServicesGroup\OrdersServices
            dockerfile: .\Dockerfile
        networks:
          - backend
        ports:
            - "8094:80"
    track-order-services:
        build:
            context: .\ProductMicroServices\ServicesGroup\TrackOrders
            dockerfile: .\Dockerfile
        networks:
          - backend
        ports:
            - "8098:80"
    gateway-service:
        build:
            context: .
            dockerfile: .\ProductMicroServices\Gateway\Dockerfile
        networks:
          - frontend
          - backend
        ports:
            - "8096:80"
networks:
    backend:
      name: api-network
    frontend:
      name: gateway-network
     